
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 20 03:20:58 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 23;
  public static final int CONST = 3;
  public static final int GRE_EQ = 31;
  public static final int NULLISH = 43;
  public static final int LPAREN = 25;
  public static final int SEMI = 7;
  public static final int CONTINUE = 18;
  public static final int LESS = 32;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 26;
  public static final int GRE = 30;
  public static final int AND = 34;
  public static final int DIFFER = 29;
  public static final int OR = 35;
  public static final int COMMA = 6;
  public static final int CLASS = 11;
  public static final int INC = 41;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int MIN = 37;
  public static final int IF = 19;
  public static final int DOT = 13;
  public static final int BOOLEAN = 46;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 24;
  public static final int EQUAL = 27;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int NUMBER = 45;
  public static final int MOD = 40;
  public static final int IDENT = 47;
  public static final int BREAK = 17;
  public static final int VOID = 10;
  public static final int COLON = 14;
  public static final int SAME = 28;
  public static final int LBRACE = 21;
  public static final int ELSE = 20;
  public static final int READ = 5;
  public static final int WHILE = 16;
  public static final int LESS_EQ = 33;
  public static final int RBRACE = 22;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int DEC = 42;
  public static final int PRINT = 4;
  public static final int DO = 15;
}

